### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by jaypeeb0917** [bundlepak/moreuseful#6]
I am not sure if I did this right, but hopefully I did. I am fairly new to this.

Brewmaster - My idea is to have the main combo and primal split combo. For example, I press letter D to initiate the main combo (you can add an option to activate primal split in the combo). Then once the primal split is activated, you can press one letter and then the primal will chase the hero you targeted without holding the key. At the same time you can add an option to force the primal to select the target with low hp or can be killed easily (this is optional). The primal option can also change target by retargeting it on a different hero you selected.

Lonedruid - Something like the arc warden script by Alfred Xia. I like how the arc warden was implemented. 

Arc Warden - Rework the script of Alfred Xia. There are times it just wonders around during fights and you lose control of it. I don't know why but I noticed it a couple of times. Maybe just optimize it? Overall this script is still working great. Maybe just a few tweaks here and there.

**Comment by bundlepak** [comment]
Today i'll finish my snippets for hake.me, then I proceed to your request. I need 1 - 2 days, 
so you'll have to wait.

**Comment by jaypeeb0917** [comment]
Take as much time as you like good sir! :) Thanks for taking time to look into this.

**Comment by wwpanbingyi** [comment]
About arc warden ,I think fooAllInOne Push script is better，but clone combo attack range is too far from the target. nullifier not work

**Comment by jaypeeb0917** [comment]
I have used foo's but the clone activation is really slow compared to Alfred's version. I just press my clone combo key once and it attacks the target.

**Comment by bundlepak** [comment]
Try Arc script, guys.

**Comment by jaypeeb0917** [comment]
I will test it now and I will give feedback :) Thanks.

**Comment by jaypeeb0917** [comment]
I just tried it now. The main hero does not combo and does not use midas. The clone is working fine but is the auto push removed?

**Comment by bundlepak** [comment]
Yes, auto push removed. It's ussless function, use travel and attack, it's not hard. 
Midas fixed.

**Comment by jaypeeb0917** [comment]
Also, I noticed that the clone is summoned automatically even if I did not intend to. Is the main hero combo also fixed.

**Comment by bundlepak** [comment]
Arc use ulti only if combo is turn on. But ok, i'll delete this function.

**Comment by jaypeeb0917** [comment]
I just tested it and now the script does not do anything. 

Here is my idea on this Arc script.
Alfred's version - really solid work but sometimes you lose control during teamfights. Maybe due to not getting updates or bug fixes? Just guessing.
Foo's version - best version but the clone activation is not as fast as alfred's version. To explain, when I press F to activate the clone and attack someone I need to press F again to make it cast the spells. All I want is to do is press F and the clone automatically attacks someone that I selected.

So ideally, I am looking at foo's version as base with alfred's clone activation as supplement. If you can point it to me, maybe I can just edit it directly on the script? 

Thanks again for your hardwork! Looking forward to your scripts!
