### ISSUE TITLE
Clinkz

### ISSUE THREAD

**Issue by ghost** [bundlepak/moreuseful#7]
Hello, it would be cool if you added for clinkz so that he did dodge Strafe:
1. Wraith King (1 ability)
2. Venga (1 ability)
3. morfling (2 and 3 ability)
4. WindRanger ( 1 ability)
5. Dragon Knight in ult ( 2 ability)
6. Chaos Knight (1 ability)

**Comment by bundlepak** [comment]
Skeleton walk fade time is too big, for dodge projectiles. It's not possible. Tested it today.
