### ISSUE TITLE
Venom

### ISSUE THREAD

**Issue by shusuka** [bundlepak/moreuseful#9]
Hello again

can i request for venomancer

for ward can last hit if attack creep and can target hero with button combo thanks

**Comment by bundlepak** [comment]
Last hitter it's too hard for me. Too many variables. I don't know any useful last hitter now. 
Veno combo, ok, i'll try do smth useful.

**Comment by shusuka** [comment]
ok maybe for venom ward priority hit enemies 1st then creep. i saw ur sub almost end. maybe i can help to extend ur sub for free if u wan.
